### ISSUE TITLE
Migration to jupyter-book [was: Sphinx contrib bibtex version]

### ISSUE THREAD

**Issue by boisgera** [ue12/python-numerique#3]
Pin down `sphinx-contrib-bibtex` to 1.0.0 ? (The Makefile in `notebooks` generates an error for me otherwise.)

**Comment by parmentelat** [comment]
Hey Seb

I suspect there might be some confusion around the tooling for producing a static version of the course

at some point we were using ipypublish; this however has gone discontinued by its maintainer, and so we went to jupyter-book

the transition however is done one repo at a time, and on an opportunistic basis
(i.e. not all repos have transitioned yet)

also in most cases the artefacts for ipypublish (index.rst, conf.py, sphinx_ipypublish_all.ext.custom.json,  etc...) are still in place, and the Makefile has seldom been cleaned up

but the rule is that if you can `jupyter-book build .` then that's the tool to use in that repo

---
the thing is the move to jb is disruptive in another way: it's much less convenient to publish the outcome on readthedocs.io

for example the last version of this repo available through ipypublish can be found here
https://ue12-python-numerique.readthedocs.io/fr/latest/

and the same built with jupyter-book is here
https://nbhosting.inria.fr/builds/ue12-python-numerique/handouts/latest/0-01-intro.html

that is, I have done a quick-and-dirty addition to nbhosting so that it can take care of building and publishing the stuff, so we can workaround the current lack of support of jb/jupyter-book in readthedocs - see https://github.com/executablebooks/jupyter-book/issues/1091 about that

all this is far from perfect, and mostly *best-effort*; there are known glitches to the resulting html, hopefully minor

---
I hope it clarifies things a bit
your feedback on all this is welcome :)

**Comment by parmentelat** [comment]
here's a thought in case we'd like to clean up our repos properly

I have another example of a repo that has gone through the same migration from sphinx/ipypublish to jupyter-book

instead of shutting down the sphinx version completely, what I did in that one was to leave on readthedocs a redirector page (see example below); that's maybe the best option

https://flotpython-slides.readthedocs.io/en/latest/

(in that repo the core content is in a subdir called `slides`)
---

**Comment by boisgera** [comment]
OK for `jupyter-book build .` (tried it and except for some minor glitches "it works"). I know that the process requires the execution of the notebooks, but I still find the process very long : 3 min between a change of the sources and the result (or the error ...), that's the promise of a painful editing process 😑. 

I wouldn't mind personally the loss of readthedocs support when all you need here is "static hosting of the latest document version" (AFAICT). You can always use a CI (such as github actions) to build the HTML output then commit to your repo (say, in the docs folder of your gh-pages branch, whose history has been erased beforehand) and configure github to expose that directly through http. This is arguably not perfect, but this is now a very popular way to deal with the production of HTML artifacts.

**Comment by parmentelat** [comment]
> 3 min between a change of the sources and the result (or the error ...), that's the promise of a painful editing process

`jb build .` should be kind-of incremental; first run is slow, but next ones are not as slow
that's the purpose of the `  execute_notebooks: cache` setting in `_config.yml`
this is not to say that I've been totally convinced that this part of the code is optimal, not predictable for that matter, but it does speed stuff up
note that the sphinx-based thing has the exact same kind of drawback, so....

> I wouldn't mind personally the loss of readthedocs support when all you need here is "static hosting of the latest document version" (AFAICT).

right

> You can always use a CI (such as github actions) to build the HTML output then commit to your repo (say, in the docs folder of your gh-pages branch, whose history has been erased beforehand) and configure github to expose that directly through http. This is arguably not perfect, but this is now a very popular way to deal with the production of HTML artifacts.

yeah well, I'm not a big fan of polluting my git repo with artefacts; nor to have to mess with gh actions; that a lot of people do it this way does not make it a good idea;) so it is what it is and good enough afaict

**Comment by boisgera** [comment]
> jb build . should be kind-of incremental; first run is slow, but next ones are not as slow
that's the purpose of the execute_notebooks: cache setting in _config.yml
this is not to say that I've been totally convinced that this part of the code is optimal, not predictable for that matter, but it does speed stuff up

You're right, it's 30 sec after the first run (with 0 cell content change). 

> note that the sphinx-based thing has the exact same kind of drawback, so....

Yes. In https://github.com/boisgera/POO-Java we make a (pandoc-based) Markdown to HTML (reveal.js) for a bunch of slides (300-400) that should correspond to the "no need to execute numeric code" case ; it runs in less than 1 sec. It allows a totally different editing process (you can make small changes and see how they look and then forget about them).

> yeah well, I'm not a big fan of polluting my git repo with artefacts; nor to have to mess with gh actions; 

I know 😀. The dedicated branch and non-accumulation of artefacts history is tidy enough for me ; YMMV ! 😉

With respect to gh actions : this is "yet-another-tool-to-learn" (😒) and I also feel the fatigue ... The only thing I have to alleviate the pain (when the time comes to build locally ... or to change the CI framework) is to make a proper build script (not a sequence of steps in gh-actions) and to use gh-pages logic only to configure the container (that's even better if the runtime dependencies are also neatly described in an external file) and to deploy the artifacts. This way, it's not that bad (see e.g. https://github.com/boisgera/POO-Java/blob/master/.github/workflows/main.yml or https://github.com/boisgera/control-engineering-with-python/blob/master/.github/workflows/build.yml).

> that a lot of people do it this way does not make it a good idea;) 

... or a bad one ! 😉

> so it is what it is and good enough afaict

If it ain't broken, don't fix it ! 😀

**Comment by boisgera** [comment]
**P.S.** In the case of https://github.com/boisgera/POO-Java, we build the HTML slides locally during the edition process, but **never** the PDF version (yeah, students & staff ask for this kind of thing) ... because this is far to slow ! But we can trust the CI to do it for me automatically on push and to deploy the result ... and this is quite nice ☺

**Comment by parmentelat** [comment]
fine; I'll leave you the *dernier mot* ;)

**Comment by parmentelat** [comment]
see d5f6095 for a cleanup in the tooling area
hth
